import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

import { ToastContainer } from "react-toastify";
// import { usePathname } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const pathname = usePathname();
  // const header = pathname == "/login" || pathname == "/forgot" ? false : true;
  return (
    <html lang="en">
      <head>
        <style
          // Inline styles for font variables to prevent hydration issues
          dangerouslySetInnerHTML={{
            __html: `
              :root {
                --font-geist-sans: ${geistSans.style.fontFamily};
                --font-geist-mono: ${geistMono.style.fontFamily};
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>{children}</div>
        <ToastContainer />
      
      </body>
    </html>
  );
}
