// app/layout.tsx or app/layout.ts
import type { Metadata } from "next";
import "./globals.css";

import Providers from "@/_common/provider";


export const metadata: Metadata = {
  title: "Grocery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
